# logging-staging.conf - Staging example bash-logger configuration file
#
# Lines starting with # or ; are comments
# Blank lines are ignored
#
# Reference: https://github.com/GingerGraham/bash-logger/blob/2.5.6/docs/configuration.md

# TODO configure example settings
[logging]
